---
title: "RWorksheet_Bernasol#3b"
author: "Shane Jhammielyn A. Bernasol"
output: pdf_document
---


1.
```{r}
respondents_data <- data.frame(
  Respondents = 1:20,
  Sex = c(2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2),
  Fathers_Occupation = c(1, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 2, 1, 3, 3, 1, 3, 1, 2, 1),
  Persons_at_Home = c(5, 7, 8, 3, 8, 5, 9, 6, 7, 8, 4, 7, 5, 4, 7, 8, 8, 3, 3, 6),
  Siblings_at_School = c(6, 4, 4, 1, 2, 1, 5, 3, 1, 2, 3, 2, 5, 5, 2, 1, 2, 5, 3, 2),
  Types_of_Houses = c(1, 2, 3, 1, 1, 3, 3, 1, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 2)
)

print(respondents_data)

```
B.
```{r}
str(respondents_data)
summary(respondents_data)
```
C.
```{r}
mean_siblings <- mean(respondents_data$Siblings_at_School)
mean_siblings

```
D.
```{r}
# Extract the first two rows and all columns
first_two_rows <- respondents_data[1:2, ]
first_two_rows

```
E.
```{r}
extracted_rows <- respondents_data[c(3, 5), c(2, 4)]
extracted_rows

```
F.
```{r}
types_houses <- respondents_data$Types_of_Houses
types_houses
```
G.
```{r}
males_farmers <- respondents_data[respondents_data$Sex == 1 & respondents_data$Fathers_Occupation == 1, ]
males_farmers

```
H.
```{r}
females_with_siblings <- respondents_data[respondents_data$Sex == 2 & respondents_data$Siblings_at_School >= 5, ]
females_with_siblings

```
2.
```{r}
df = data.frame(Ints=integer(),
Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)
print("Structure of the empty dataframe:")
print(str(df))

```
3A.
```{r}
options(repos = c(CRAN = "https://cran.rstudio.com/"))
install.packages("readxl")
library(readxl)
household_data <- read.csv("/cloud/project/Worksheet 3B/HouseholdData.csv")
head(household_data)  

```
3B.
```{r}
unique(household_data$Sex)

household_data$Sex <- ifelse(tolower(household_data$Sex) == "male", 1,
                              ifelse(tolower(household_data$Sex) == "female", 2, NA))
household_data$Sex <- factor(household_data$Sex, levels = c(1, 2), labels = c("Male", "Female"))
head(household_data)
unique(household_data$Sex)
```
2C.

```{r}
str(household_data)
head(household_data)

unique(household_data$Types_of_Houses)

if ("Types_of_Houses" %in% names(household_data)) {
    household_data$Types_of_Houses <- factor(household_data$Types_of_Houses, 
                                              levels = c("Wood", "Concrete", "Semi-Concret"),
                                              labels = c(1, 2, 3))
    
    household_data$Types_of_Houses <- as.integer(household_data$Types_of_Houses)

    print(head(household_data))
} else {
    print("The column 'Types_of_Houses' does not exist in the data frame.")
}

```
3D.
```{r}
str(household_data)
head(household_data)
names(household_data)[names(household_data) == "Fathers Occupation"] <- "Fathers_Occupation"
names(household_data)

if ("Fathers_Occupation" %in% names(household_data)) {
    household_data$Fathers_Occupation <- factor(household_data$Fathers_Occupation, 
                                                 levels = c("Farmer", "Driver", "Others"),
                                                 labels = c(1, 2, 3))
    
    household_data$Fathers_Occupation <- as.integer(household_data$Fathers_Occupation)
    print(head(household_data))
} else {
    print("The column 'Fathers_Occupation' still does not exist in the data frame.")
}

 
```
3E.
```{r}
str(household_data)
names(household_data)
head(household_data)
females_with_driver_father <- subset(household_data, Sex == "Female" & `Fathers.Occupation` == "Driver")
```
# f. Select respondents with 5 or more siblings attending school


# 4. Interpret the graph
```{r}
siblings_5_or_more <- subset(respondents_data, Siblings_at_School >= 5)
print(siblings_5_or_more)
```

```{r}
df <- data.frame(
Name = c("Alice", "Bob", "Charlie", "David"),
Siblings = c(2, 3, 1, 4))
```



